### ISSUE TITLE
集群控制面故障替换方案调研

### ISSUE THREAD

**Issue by pwkuan** [TencentBlueKing/bk-bcs#2361]
输出文档
- [x] master节点已验证
- [x] bcs-apiserver-proxy外部出包

注意备份

**Comment by pwkuan** [comment]
1. 控制面扩容新节点
2. 控制面缩容故障节点
3. 修改kube-apiserver高可用配置

**Comment by abstractmj** [comment]
* kube-apiserver高可用，本周完成
* 单独可运行脚本输出，本周明确分工
