### ISSUE TITLE
集群巡检工具

### ISSUE THREAD

**Issue by pwkuan** [TencentBlueKing/bk-bcs#2367]
部署脚本
- [x] 组件配置一致性检查
- [x] 集群可用性监测
- [x] 系统应用检测（Pod状态/服务）

**Comment by pwkuan** [comment]
@wingyao666 本周PR

**Comment by abstractmj** [comment]
* 组件配置一致性检查 和 集群可用性监测 本周完成
* 系统应用检测（Pod状态/服务）今天PR
