### ISSUE TITLE
新版部署方案产品化验证

### ISSUE THREAD

**Issue by pwkuan** [TencentBlueKing/bk-bcs#2407]
- [x] 可在产品页面上创建集群/删除集群/添加节点/删除节点 
- [x] 可在标准运维页面上创建集群/删除集群/添加节点/删除节点 
       * 1.20～1.24双栈

**Comment by abstractmj** [comment]
- [x] 可在标准运维页面上创建集群/删除集群/添加节点/删除节点 
       * 1.20～1.24双栈

**Comment by pwkuan** [comment]
- [x] 标准运维流程导入至公共流程中
